# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HumanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(choices=[('0', '男'), ('1', '女')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('birthady', models.DateField()),
                ('human', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='text.Human')),
            ],
        ),
        migrations.CreateModel(
            name='Publiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=60)),
                ('company_city', models.CharField(max_length=50)),
                ('company_web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_name', models.CharField(max_length=100)),
                ('Work_date', models.DateField()),
                ('Work_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Publiser')),
                ('Work_human', models.ManyToManyField(to='text.Human')),
            ],
        ),
    ]
