# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': '姓名', 'verbose_name_plural': '姓名'},
        ),
        migrations.AlterModelOptions(
            name='humandetail',
            options={'verbose_name': '人员信息', 'verbose_name_plural': '人员信息'},
        ),
        migrations.AlterModelOptions(
            name='publiser',
            options={'verbose_name': '公司信息', 'verbose_name_plural': '公司信息'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '工作信息', 'verbose_name_plural': '工作信息'},
        ),
        migrations.AlterField(
            model_name='humandetail',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=1),
        ),
        migrations.AlterField(
            model_name='publiser',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='公司名'),
        ),
    ]
