# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20170123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='humandetail',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='humandetail',
            name='birthady',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='humandetail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='humandetail',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女'), (2, '未知')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='publiser',
            name='company_address',
            field=models.CharField(max_length=60, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='publiser',
            name='company_city',
            field=models.CharField(max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='publiser',
            name='company_web',
            field=models.URLField(verbose_name='公司主页'),
        ),
    ]
