#!/usr/bin/env python
# coding=utf-8

panel_info = {u'审批系统': {'name': u'审批系统', 
                            'url': '/review/reviewManage', 
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 2,
                            'sub_info': {u'我的审批': '/review/sp_wdsp',
                                         u'数据统计': '/review/reviewManage',
                                         u'所有审批': '/review/sp_sysp'}},
              u'进件系统': {'name': u'进件系统',
                            'url': '/order/intoManage',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 1,
                            'sub_info': {
                                         u'数据统计': '/order/intoManage',
                                         u'订单列表': '/order/jinj_ddlb'}},
              u'运营系统': {'name': u'运营系统',
                            'url': '/operation/yYManage',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 3,
                            'sub_info': {u'代扣订单': '/operation/yy_dkdd',
                                         u'数据统计': '/operation/yYManage',
                                         u'代付订单': '/operation/yy_dfdd'}},
              u'催收系统': {'name': u'催收系统',
                            'url': '/collection/collectionManage',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 4,
                            'sub_info': {u'我的催收': '/collection/cs_wdcs',
                                         u'数据统计': '/collection/collectionManage',
                                         u'所有催收': '/collection/cs_sycs',
                                         u'数据导入': '/collection/cs_sjdr',
                                         u'模板配置': '/collection/cs_mbpz'}},
              u'财务系统': {'name': u'财务系统',
                            'url': '/audit/cWManage',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 5,
                            'sub_info': {u'应收账单': '/audit/cw_yszd',
                                         u'数据统计': '/audit/cWManage',
                                         u'实收账单': '/audit/cw_sszd',
                                         u'财务复核': '/audit/cw_cwfh'}},
              u'客服系统': {'name': u'客服系统',
                            'url': '/custom/test',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 6,
                            'sub_info': {u'搜索订单': 'custom/test'}},
              u'员工系统': {'name': u'员工系统',
                            'url': '/employee/employeesystem',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 7,
                            'sub_info': {u'新增员工': '/employee/yg_xzyg',
                                         u'员工维护': '/employee/yg_ygwh'}},
              u'配置系统': {'name': u'配置系统',
                            'url': '/config_center/peizhicenter',
                            'selected_icon': 'xxx.png',
                            'unselected_icon': 'xxx.png',
                            'order': 8,
                            'sub_info': {u'用户组与权限': '/employee/pz_hyzqx',
                                         u'子系统配置': '/config_center/pz_system',
                                         u'贷款策略配置': '/loan/loanstrlist'}}}


